{% set version = "0.3.0" %}

package:
  name: jupyterlab-gt-coar-theme
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/j/jupyterlab-gt-coar-theme/jupyterlab-gt-coar-theme-{{ version }}.tar.gz
  sha256: 0d74f0f9cafc8c282d400d51550cb82c2d7b8628ac3ea98f91aed1137315b47e

build:
  number: 1
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - jupyterlab >=3,<4
    - python >={{ python_min }}

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - jupyterlab_gt_coar_theme
  commands:
    - pip check
    - jupyter labextension list

about:
  home: https://github.com/gt-coar/jupyterlab-gt-coar-theme
  summary: an unofficial Georgia Tech theme for JupyterLab
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - bollwyvl
