{% set name = "jupyterlab-gt-coar-theme" %}
{% set version = "0.3.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0d74f0f9cafc8c282d400d51550cb82c2d7b8628ac3ea98f91aed1137315b47e

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - jupyterlab >=3,<4
    - python >={{ python_min }}

test:
  imports:
    - jupyterlab_gt_coar_theme
  commands:
    - pip check
    - jupyter labextension list
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/gt-coar/jupyterlab-gt-coar-theme
  summary: an unofficial Georgia Tech theme for JupyterLab
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - bollwyvl
